/*
 * Enviroment.java
 *
 * Created on 10 de Dezembro de 2008, 01:32
 */

package br.pucpr.ppgia.prototipo.gui;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.XYSeriesCollection;

import br.pucpr.ppgia.prototipo.util.Config;


/**
 *
 * @author  Vanderson Bot�lho
 */
public abstract class AbstractGUI extends javax.swing.JFrame {
    
   
	private static final long serialVersionUID = 1L;
	/** Creates new form Enviroment */
    public AbstractGUI() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" C�digo Gerado ">//GEN-BEGIN:initComponents
    private void initComponents() {
        chartFrame = new javax.swing.JFrame();
        label1 = new java.awt.Label();
        progress = new javax.swing.JProgressBar();
        jPanel3 = new javax.swing.JPanel();
        btRun = new java.awt.Button();
        cbCenario = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        lbDate = new javax.swing.JLabel();

        chartFrame.setName("chartFrame");
        chartFrame.getAccessibleContext().setAccessibleName("chartFrame");
        label1.setText("dfsfs");

        javax.swing.GroupLayout chartFrameLayout = new javax.swing.GroupLayout(chartFrame.getContentPane());
        chartFrame.getContentPane().setLayout(chartFrameLayout);
        chartFrameLayout.setHorizontalGroup(
            chartFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chartFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(359, Short.MAX_VALUE))
        );
        chartFrameLayout.setVerticalGroup(
            chartFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chartFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(270, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema CRONOS");
        setName("mainFrame");
        getAccessibleContext().setAccessibleName("mainFrame");
        progress.setBackground(new java.awt.Color(204, 204, 204));

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btRun.setActionCommand("d");
        btRun.setBackground(new java.awt.Color(212, 208, 200));
        btRun.setForeground(new java.awt.Color(0, 0, 0));
        btRun.setLabel("Run");
        btRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRunActionPerformed(evt);
            }
        });

        cbCenario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "cenario_001.properties", "cenario_002.properties", "cenario_003.properties", "cenario_004.properties", "cenario_005.properties" }));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbDate.setFont(new java.awt.Font("Arial", 1, 24));
        lbDate.setForeground(new java.awt.Color(0, 0, 255));
        lbDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
       //lbDate.setText("dd/mm/aaaa");
        lbDate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbDate, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btRun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbCenario, 0, 176, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(cbCenario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btRun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(progress, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(progress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRunActionPerformed
    	System.err.println("selecionado= " + cbCenario.getSelectedItem().toString());
    	Config.loadCenario(cbCenario.getSelectedItem().toString());
        XYSeriesCollection xyDataset = getAllSeries();
        JFreeChart chart = ChartFactory.createXYLineChart(" ", "Tempo", "Ganho de Utilidade (UG)", xyDataset, PlotOrientation.VERTICAL, true, true, false);
        chartFrame = new ChartFrame("CRONOS Chart",chart);        
        chartFrame.setBounds(this.getBounds().x, this.getBounds().y + this.getBounds().height, this.getBounds().width * 3, this.getBounds().height * 4);
        chartFrame.setVisible(true);
        System.err.println("selecionado= " + cbCenario.getSelectedItem().toString());
        runSystem(cbCenario.getSelectedItem().toString());
    }//GEN-LAST:event_btRunActionPerformed
    
    
    
    
    protected abstract void runSystem(String cenario);
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Enviroment().setVisible(true);
            }
        });
    }
    
    protected abstract XYSeriesCollection getAllSeries();
    
    // Declara��o de vari�veis - n�o modifique//GEN-BEGIN:variables
    private java.awt.Button btRun;
    public javax.swing.JComboBox cbCenario;
    private javax.swing.JFrame chartFrame;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private java.awt.Label label1;
    public javax.swing.JLabel lbDate;
    public javax.swing.JProgressBar progress;
    // Fim da declara��o de vari�veis//GEN-END:variables
    
    
    
}
